project_name: terraform-provider-cloud-deploy

builds:
  - binary: "terraform-provider-cloud-deploy_{{.Tag}}"
    goos:
      - freebsd
      - windows
      - linux
      - solaris
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: solaris
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: solaris
        goarch: arm

archive:
  format: zip
  files:
  - none*

release:
  draft: true

  github:
    owner: claranet
    name: terraform-provider-cloud-deploy